# Generated by Django 4.0.4 on 2022-04-23 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_id_telegram_ids_users_and_more'),
        ('paids', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='payer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payer+', to='users.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='taker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker+', to='users.table'),
        ),
    ]
