# Generated by Django 4.0.4 on 2022-04-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_id_telegram_ids_users_and_more'),
        ('paids', '0003_rename_payer_id_table_payer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='fuller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuller+', to='users.table'),
        ),
        migrations.AddField(
            model_name='table',
            name='sanctioner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanctioner+', to='users.table'),
        ),
    ]
