# Generated by Django 4.0.4 on 2022-05-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_users_id_telegram_ids_users_and_more'),
        ('paids', '0004_table_fuller_table_sanctioner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.BigIntegerField()),
                ('what', models.BigIntegerField()),
                ('initial', models.BigIntegerField()),
                ('overall', models.BigIntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.table')),
            ],
        ),
    ]
