# Generated by Django 4.0.4 on 2022-05-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0006_currency_alter_money_date_alter_money_what'),
    ]

    operations = [
        migrations.RenameField(
            model_name='money',
            old_name='what',
            new_name='currency',
        ),
    ]
