# Generated by Django 4.0.4 on 2022-05-09 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0008_remove_table_fuller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='overall',
        ),
    ]
