# Generated by Django 4.0.4 on 2022-05-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0009_remove_money_overall'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paids.currency'),
        ),
    ]
