# Generated by Django 4.0.4 on 2022-06-02 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paids', '0010_table_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='initial',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='cash',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='diliver_paid',
            field=models.FloatField(null=True),
        ),
    ]
