# Generated by Django 4.0.3 on 2022-04-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='creator_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator+', to='users.table'),
        ),
        migrations.AlterField(
            model_name='table',
            name='linked_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked+', to='users.table'),
        ),
    ]
