# Generated by Django 4.0.3 on 2022-04-20 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_alter_table_creator_id_alter_table_linked_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='creator_id',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='linked_id',
            new_name='linked',
        ),
    ]
